falco:
  ebpf:
    enabled: true
  driver:
    kind: modern_bpf
  json_output: true
  stdout_output:
    enabled: true        # 이렇게 "enabled: true" 구조로 들어가야 함
    format: json

file_output:
  enabled: true
  keep_alive: true
  filename: /var/log/falco-events.log

extraVolumeMounts:
  - name: varlog
    mountPath: /var/log

extraVolumes:
  - name: varlog
    hostPath:
      path: /var/log
      type: Directory